# Generated by Django 5.0.2 on 2024-07-12 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 13, 16, 0, 24, 568904, tzinfo=datetime.timezone.utc)),
        ),
    ]
